version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Performing manual install of compose cli" &&
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - &&
      - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" &&
      - sudo apt-get update -y &&
      - sudo sudo apt-get install docker-ce docker-ce-cli containerd.io -y &&
      - sudo curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh &
      - sudo curl -L https://github.com/docker/compose/releases/download/v2.9.0/docker-compose-linux-x86_64 -o /usr/bin/docker-compose
      - sudo chmod +x /usr/bin/docker-compose
      - export PATH="${HOME}/bin:$PATH"
      - which docker
      - which docker-compose 
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD

  build:
    commands:
      - echo Build started on `date`
      - docker/docker-compose build
      - echo "Tagging Docker image for Docker Hub"
      - docker images
      - docker tag src_backend:latest ${DOCKERHUB_USERNAME}/ubuntu-backend:${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - docker tag src_frontend:latest ${DOCKERHUB_USERNAME}/ubuntu-frontend:${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - docker push ${DOCKERHUB_USERNAME}/ubuntu-backend:${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - docker push ${DOCKERHUB_USERNAME}/ubuntu-frontend:${CODEBUILD_RESOLVED_SOURCE_VERSION}
  
  post_build:
    commands:
      - echo "build successful"
   